<a href="https://colab.research.google.com/github/leehyeonjin99/BOOSTCAMP_AI_Tech_Study_Diary/blob/main/%ED%95%99%EC%8A%B5%EC%A0%95%EB%A6%AC/Pytorch/Pytorch_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor

In [1]:
# numpy-ndarray
import numpy as np
n_array=np.arange(10).reshape(2,5)
print(n_array)
print(f"ndim : {n_array.ndim}, shape : {n_array.shape}")

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim : 2, shape : (2, 5)


In [2]:
# pytorch-tensor 
import torch
t_array=torch.FloatTensor(n_array)
print(t_array)
print(f"ndim : {t_array.ndim}, shape : {t_array.shape}")

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim : 2, shape : torch.Size([2, 5])


In [3]:
# data to tensor
data=[[3,5],[10,5]]
x_data=torch.tensor(data)
x_data

tensor([[ 3,  5],
        [10,  5]])

In [4]:
# ndarray to tensor : from_numpy() → 2nd cell의 FloatTensor() 사용 가능
nd_array_ex=np.array(data)
tensor_array=torch.from_numpy(nd_array_ex)
tensor_array

tensor([[ 3,  5],
        [10,  5]])

### Tensor data types

- tensor의 데이터 타입은 numpy와 동일하다.
- GPU 사용 가능한 data type이 존재한다.

### Numpy like operations

In [5]:
data=[[3,5,20],[10,5,50],[1,5,10]]
x_data=torch.tensor(data)
x_data

tensor([[ 3,  5, 20],
        [10,  5, 50],
        [ 1,  5, 10]])

In [6]:
# slicing
x_data[1:]

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [7]:
x_data[:2,1:]

tensor([[ 5, 20],
        [ 5, 50]])

In [8]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [9]:
# 같은 shape의 tensor 만들기
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [10]:
# tensor to array
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]])

In [11]:
# check shape
x_data.shape

torch.Size([3, 3])

In [12]:
# check dimension
x_data.ndim

2

In [13]:
# check type
x_data.dtype

torch.int64

**pytorch의 tensor는 GPU에 올려서 사용가능**

`x_data.device` : x_data를 메모리에 올릴지 GPU에 올릴지 확인하는 property
- GPU : cuda
- CPU : cpu

In [14]:
x_data.device

device(type='cpu')

In [15]:
if torch.cuda.is_available():
    x_data_cuda=x_data.to('cuda')

x_data_cuda.device

device(type='cuda', index=0)

### Tensor handling
`view` : numpy의 reshape와 동일하게 tensor의 shape를 변환

`squeeze` : 차원의 개수가 1인 차원을 삭제(압축)

`unsqueeze` : 차원의 개수가 1인 차원을 추가

In [16]:
tensor_ex=torch.rand(size=(2,3,2))
tensor_ex

tensor([[[0.6065, 0.8744],
         [0.4677, 0.4870],
         [0.9951, 0.8848]],

        [[0.2925, 0.8909],
         [0.0502, 0.4510],
         [0.8878, 0.8466]]])

#### view()
pytorch에서 reshape와 view의 차이
- view() : 기존의 데이터와 같은 메모리 공간을 공유하며 stride 크기만 변경하여 보여주기만 다르게 한다. 따라서, contigious 해야만 동작하며 아닌 경우 에러가 발생한다.
- reshape() : contiguous tensor에서는 view와 동일하게 작동한다. non-contiguous tensor에서는 data를 copy한다.

> **Contiguous vs Noncontiguous**
> 
> - contiguous : Torch의 Array의 값이 연속적인 메모리 위치를 가지는 경우  
> - noncontigous : Array의 값이 뒤섞여 메모리 위치를 가지는 경우
> 
> <img src="https://blog.kakaocdn.net/dn/dgs983/btrcuJek14h/mLMhSJyZfS2ZdJZX497n90/img.png" width=400>

reference : 
[Week_3 Pytorch - view vs. reshape](https://memesoo99.tistory.com/50)

In [17]:
tensor_ex.view((-1,6))

tensor([[0.6065, 0.8744, 0.4677, 0.4870, 0.9951, 0.8848],
        [0.2925, 0.8909, 0.0502, 0.4510, 0.8878, 0.8466]])

In [18]:
tensor_ex.reshape((-1,6))

tensor([[0.6065, 0.8744, 0.4677, 0.4870, 0.9951, 0.8848],
        [0.2925, 0.8909, 0.0502, 0.4510, 0.8878, 0.8466]])

In [19]:
a=torch.zeros(3,2)
b=a.view(2,3)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [20]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [21]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [22]:
a=torch.zeros(3,2)
b=a.t().reshape(6)
a.fill_(1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [23]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [24]:
b

tensor([0., 0., 0., 0., 0., 0.])

#### squeeze(), unsqueeze()

<img src="https://i.stack.imgur.com/9AJJA.png" width=400>

In [25]:
tensor_ex=torch.rand(size=(2,1,2))
print(f"before squeezing : \n{tensor_ex}\nafter squeezing : \n{tensor_ex.squeeze()}")

before squeezing : 
tensor([[[0.9101, 0.8124]],

        [[0.3238, 0.2744]]])
after squeezing : 
tensor([[0.9101, 0.8124],
        [0.3238, 0.2744]])


In [26]:
tensor_ex=torch.rand(size=(2,2))
print(f"before unsqueeze(0) : \n{tensor_ex.shape}\nafter unsqueeze(0) : \n{tensor_ex.unsqueeze(0).shape}")

before unsqueeze(0) : 
torch.Size([2, 2])
after unsqueeze(0) : 
torch.Size([1, 2, 2])


In [27]:
tensor_ex=torch.rand(size=(2,2))
print(f"before unsqueeze(1) : \n{tensor_ex.shape}\nafter unsqueeze(1) : \n{tensor_ex.unsqueeze(1).shape}")

before unsqueeze(1) : 
torch.Size([2, 2])
after unsqueeze(1) : 
torch.Size([2, 1, 2])


In [28]:
tensor_ex=torch.rand(size=(2,2))
print(f"before unsqueeze(1) : \n{tensor_ex.shape}\nafter unsqueeze(2) : \n{tensor_ex.unsqueeze(2).shape}")

before unsqueeze(1) : 
torch.Size([2, 2])
after unsqueeze(2) : 
torch.Size([2, 2, 1])


### Tensor Operations

In [29]:
n1=np.arange(10).reshape(2,5)
n2=np.arange(10).reshape(5,2)
t1=torch.FloatTensor(n1)
t2=torch.FloatTensor(n2)

In [30]:
t1

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [31]:
t2

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [32]:
t1+t1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

In [33]:
t1-t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [34]:
t1+10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

- **행렬곱셈 연산**은 dot이 아닌 mm 사용

In [35]:
t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [36]:
t1.dot(t2)

RuntimeError: ignored

In [37]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

- **벡터 및 스칼라 곱셈 연산**은 mm이 아닌 dot 사용

In [38]:
a=torch.rand(10)
b=torch.rand(10) 

In [39]:
a.dot(b)

tensor(3.5159)

In [40]:
a.mm(b)

RuntimeError: ignored

- matmul은 broadingcasting 지원

In [41]:
a.matmul(b)

tensor(3.5159)

In [42]:
a=torch.rand(5,2,3)
b=torch.rand(3)

In [43]:
a

tensor([[[0.0099, 0.4479, 0.2278],
         [0.0149, 0.3185, 0.1659]],

        [[0.3220, 0.6110, 0.2847],
         [0.2368, 0.7291, 0.3863]],

        [[0.0046, 0.8218, 0.9926],
         [0.4649, 0.0434, 0.7985]],

        [[0.5856, 0.4211, 0.3403],
         [0.0330, 0.2954, 0.8606]],

        [[0.6048, 0.1355, 0.6929],
         [0.6046, 0.1465, 0.6185]]])

In [44]:
b

tensor([0.5853, 0.6673, 0.1854])

In [45]:
a.mm(b)

RuntimeError: ignored

In [46]:
a.matmul(b)

tensor([[0.3469, 0.2520],
        [0.6490, 0.6968],
        [0.7351, 0.4491],
        [0.6868, 0.3760],
        [0.5728, 0.5663]])

In [47]:
# mm의 broadcasting 확인
print(a[0].mm(torch.unsqueeze(b,1)).squeeze())
print(a[1].mm(torch.unsqueeze(b,1)).squeeze())
print(a[2].mm(torch.unsqueeze(b,1)).squeeze())
print(a[3].mm(torch.unsqueeze(b,1)).squeeze())
print(a[4].mm(torch.unsqueeze(b,1)).squeeze())

tensor([0.3469, 0.2520])
tensor([0.6490, 0.6968])
tensor([0.7351, 0.4491])
tensor([0.6868, 0.3760])
tensor([0.5728, 0.5663])


### Tensor operations for ML/DL formula
`nn.functional` 모듈

In [48]:
import torch
import torch.nn.functional as F

tensor=torch.FloatTensor([0.5,0.7,0.1])
h_tensor=F.softmax(tensor, dim=0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [49]:
y=torch.randint(5,(10,5))
print(y)
y_label=y.argmax(dim=1)
y_label

tensor([[2, 0, 4, 2, 2],
        [3, 2, 0, 0, 4],
        [4, 3, 1, 0, 0],
        [1, 0, 0, 0, 3],
        [0, 2, 3, 3, 1],
        [4, 0, 2, 3, 1],
        [2, 1, 2, 2, 3],
        [3, 0, 1, 3, 4],
        [3, 4, 0, 2, 2],
        [4, 3, 3, 1, 2]])


tensor([2, 4, 0, 4, 2, 0, 4, 4, 1, 0])

In [50]:
F.one_hot(y_label)

tensor([[0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0]])

In [51]:
import itertools
a=[1,2,3]
b=[4,5]
list(itertools.product(a,b))

[(1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5)]

In [52]:
tensor_a=torch.tensor(a)
tensor_b=torch.tensor(b)
torch.cartesian_prod(tensor_a,tensor_b)

/usr/local/lib/python3.7/dist-packages/torch/functional.py:1069: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.cartesian_prod(tensors)  # type: ignore[attr-defined]


tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5]])

### AutoGrad

$$ y={w}^{2}$$
$$z=10*y+25$$
$$z=10*{w}^2+25$$

In [53]:
w=torch.tensor(2., requires_grad=True)
y=w**2
z=10*y+25
z.backward()
w.grad

tensor(40.)

$$Q=3a^3-b^2$$

In [54]:
a=torch.tensor([2.,3.], requires_grad=True)
b=torch.tensor([6.,4.],requires_grad=True)
Q=3*a**3-b**2
# Q는 벡터이므로 Q.backward()의 gradient 인자를 명시적으로 전달해야한다.
external_grad=torch.tensor([1.,1.])
Q.backward(gradient=external_grad)

In [55]:
a.grad

tensor([36., 81.])

In [56]:
b.grad

tensor([-12.,  -8.])