In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])

W=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)

optimizer=optim.SGD([W,b],lr=0.01)
epochs=1999
for epoch in range(epochs):

  hypothesis=W*x_train+b
  cost=torch.mean((hypothesis-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0:
    print(f"Epoch: {epoch:4d}/{epochs} W: {W.item():.3f}. b: {b.item():.3f}, Cost: {cost.item():.6f}")


Epoch:    0/1999 W: 0.187. b: 0.080, Cost: 18.666666
Epoch:  100/1999 W: 1.746. b: 0.578, Cost: 0.048171
Epoch:  200/1999 W: 1.800. b: 0.454, Cost: 0.029767
Epoch:  300/1999 W: 1.843. b: 0.357, Cost: 0.018394
Epoch:  400/1999 W: 1.876. b: 0.281, Cost: 0.011366
Epoch:  500/1999 W: 1.903. b: 0.221, Cost: 0.007024
Epoch:  600/1999 W: 1.924. b: 0.174, Cost: 0.004340
Epoch:  700/1999 W: 1.940. b: 0.136, Cost: 0.002682
Epoch:  800/1999 W: 1.953. b: 0.107, Cost: 0.001657
Epoch:  900/1999 W: 1.963. b: 0.084, Cost: 0.001024
Epoch: 1000/1999 W: 1.971. b: 0.066, Cost: 0.000633
Epoch: 1100/1999 W: 1.977. b: 0.052, Cost: 0.000391
Epoch: 1200/1999 W: 1.982. b: 0.041, Cost: 0.000242
Epoch: 1300/1999 W: 1.986. b: 0.032, Cost: 0.000149
Epoch: 1400/1999 W: 1.989. b: 0.025, Cost: 0.000092
Epoch: 1500/1999 W: 1.991. b: 0.020, Cost: 0.000057
Epoch: 1600/1999 W: 1.993. b: 0.016, Cost: 0.000035
Epoch: 1700/1999 W: 1.995. b: 0.012, Cost: 0.000022
Epoch: 1800/1999 W: 1.996. b: 0.010, Cost: 0.000013
Epoch: 1900

In [4]:
# optimizer.zero_grad()가 필요한 이유

import torch
w=torch.tensor(2.0, requires_grad=True)

epochs=20
for epoch in range(epochs+1):
  z=2*w
  z.backward()
  print("수식을 w로 미분한 값 :",w.grad.item())

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


In [5]:
## 자동미분

import torch
w=torch.tensor(2.0, requires_grad=True)
y=w**2
z=2*y+5
z.backward()
print('수식을 w로 미분한 값 :',w.grad.item())

수식을 w로 미분한 값 : 8.0


In [6]:
## 다중 선형 회귀
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [7]:
w1=torch.zeros(1,requires_grad=True)
w2=torch.zeros(1,requires_grad=True)
w3=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)

In [8]:
optimizer=optim.SGD([w1,w2,w3,b],lr=1e-5)
epochs=1000

for epoch in range(epochs+1):
  hypothesis=x1_train*w1+x2_train*w2+x3_train*w3+b
  cost=torch.mean((hypothesis-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


In [9]:
## 다중 선형 회귀 : 행렬 연산
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [10]:
W=torch.zeros((3,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)

In [11]:
optimizer=optim.SGD([W,b],lr=1e-5)
epochs=1000

for epoch in range(epochs+1):
  hypothesis=torch.matmul(x_train,W)+b
  cost=torch.mean((hypothesis-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{epochs} hypothesis : {hypothesis.squeeze().detach()} Cost: {cost:.6f}')

Epoch    0/1000 hypothesis : tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch  100/1000 hypothesis : tensor([154.0433, 185.0925, 175.8312, 198.5701, 141.2221]) Cost: 5.754573
Epoch  200/1000 hypothesis : tensor([154.0278, 185.0649, 175.9335, 198.5128, 141.2284]) Cost: 5.512386
Epoch  300/1000 hypothesis : tensor([154.0120, 185.0385, 176.0329, 198.4569, 141.2353]) Cost: 5.281667
Epoch  400/1000 hypothesis : tensor([153.9960, 185.0133, 176.1295, 198.4022, 141.2426]) Cost: 5.061907
Epoch  500/1000 hypothesis : tensor([153.9797, 184.9892, 176.2233, 198.3488, 141.2504]) Cost: 4.852424
Epoch  600/1000 hypothesis : tensor([153.9632, 184.9662, 176.3143, 198.2966, 141.2586]) Cost: 4.652731
Epoch  700/1000 hypothesis : tensor([153.9465, 184.9442, 176.4029, 198.2456, 141.2672]) Cost: 4.462265
Epoch  800/1000 hypothesis : tensor([153.9296, 184.9232, 176.4888, 198.1958, 141.2762]) Cost: 4.280604
Epoch  900/1000 hypothesis : tensor([153.9126, 184.9032, 176.5724, 198.1471, 141.2855]) Cost: 4.107

In [12]:
## 선형 회귀 : nn.Module
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])

model=nn.Linear(1,1)

In [13]:
list(model.parameters())

[Parameter containing:
 tensor([[0.5153]], requires_grad=True), Parameter containing:
 tensor([-0.4414], requires_grad=True)]

In [14]:
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)
epochs=2000

for epoch in range(epochs):
  prediction=model(x_train)
  cost=F.mse_loss(prediction, y_train)
  
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0:
    print(f"Epoch {epoch}/{epochs} Cost: {cost:.6f}")

Epoch 0/2000 Cost: 13.103541
Epoch 100/2000 Cost: 0.002791
Epoch 200/2000 Cost: 0.001724
Epoch 300/2000 Cost: 0.001066
Epoch 400/2000 Cost: 0.000658
Epoch 500/2000 Cost: 0.000407
Epoch 600/2000 Cost: 0.000251
Epoch 700/2000 Cost: 0.000155
Epoch 800/2000 Cost: 0.000096
Epoch 900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000


In [15]:
new_var=torch.Tensor([4.0])
pred_y=model(new_var)
print("훈련 후 입력이 4일 때의 예측값 :",pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([7.9989], grad_fn=<AddBackward0>)


In [16]:
list(model.parameters())

[Parameter containing:
 tensor([[1.9994]], requires_grad=True), Parameter containing:
 tensor([0.0014], requires_grad=True)]

In [17]:
## 다중 선형 회귀 : nn.Model
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

model=nn.Linear(3,1)
optimizer=torch.optim.SGD(model.parameters(),lr=1e-5)
epochs=2000

for epoch in range(epochs+1):
  prediction=model(x_train)
  cost=F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0:
    print(f"Epoch {epoch:4d}/{epochs} Cost : {cost:11.6f}")

Epoch    0/2000 Cost : 31667.597656
Epoch  100/2000 Cost :    0.225993
Epoch  200/2000 Cost :    0.223911
Epoch  300/2000 Cost :    0.221941
Epoch  400/2000 Cost :    0.220059
Epoch  500/2000 Cost :    0.218271
Epoch  600/2000 Cost :    0.216575
Epoch  700/2000 Cost :    0.214950
Epoch  800/2000 Cost :    0.213413
Epoch  900/2000 Cost :    0.211952
Epoch 1000/2000 Cost :    0.210560
Epoch 1100/2000 Cost :    0.209232
Epoch 1200/2000 Cost :    0.207967
Epoch 1300/2000 Cost :    0.206761
Epoch 1400/2000 Cost :    0.205619
Epoch 1500/2000 Cost :    0.204522
Epoch 1600/2000 Cost :    0.203484
Epoch 1700/2000 Cost :    0.202485
Epoch 1800/2000 Cost :    0.201542
Epoch 1900/2000 Cost :    0.200635
Epoch 2000/2000 Cost :    0.199769


In [18]:
new_var=torch.Tensor([73,80,75])
pred_y=model(new_var)
print("훈련 후 입력이 73,80,75일 때의 예측값 :",pred_y.item())

훈련 후 입력이 73,80,75일 때의 예측값 : 151.2305450439453


In [19]:
list(model.parameters())

[Parameter containing:
 tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
 tensor([0.2802], requires_grad=True)]

In [20]:
## 클래스로 파이토치 모델 구현하기 : input_dim=1, output_dim=1

class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(1,1)

  def forward(self, x):
    return self.linear(x)

In [21]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

model=LinearRegressionModel()
optimizer=torch.optim.SGD(model.parameters(),lr=0.01)
epochs=2000

for epoch in range(epochs+1):
  prediction=model(x_train)
  cost=F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, epochs, cost.item()))

Epoch    0/2000 Cost: 33.679783
Epoch  100/2000 Cost: 0.223159
Epoch  200/2000 Cost: 0.137899
Epoch  300/2000 Cost: 0.085213
Epoch  400/2000 Cost: 0.052656
Epoch  500/2000 Cost: 0.032539
Epoch  600/2000 Cost: 0.020107
Epoch  700/2000 Cost: 0.012425
Epoch  800/2000 Cost: 0.007678
Epoch  900/2000 Cost: 0.004744
Epoch 1000/2000 Cost: 0.002932
Epoch 1100/2000 Cost: 0.001812
Epoch 1200/2000 Cost: 0.001119
Epoch 1300/2000 Cost: 0.000692
Epoch 1400/2000 Cost: 0.000427
Epoch 1500/2000 Cost: 0.000264
Epoch 1600/2000 Cost: 0.000163
Epoch 1700/2000 Cost: 0.000101
Epoch 1800/2000 Cost: 0.000062
Epoch 1900/2000 Cost: 0.000039
Epoch 2000/2000 Cost: 0.000024


In [22]:
## 클래스로 파이토치 모델 구현하기 : 다중 선형 회귀

class MultivariateLinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(3,1)
  
  def forward(self,x):
    return self.linear(x)

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

model=MultivariateLinearRegression()
optimizer=torch.optim.SGD(model.parameters(),lr=1e-5)
epochs=2000

for epoch in range(epochs):
  prediction=model(x_train)
  cost=F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, epochs, cost.item()))

Epoch    0/2000 Cost: 22642.416016
Epoch  100/2000 Cost: 4.976951
Epoch  200/2000 Cost: 4.733481
Epoch  300/2000 Cost: 4.502824
Epoch  400/2000 Cost: 4.284275
Epoch  500/2000 Cost: 4.077209
Epoch  600/2000 Cost: 3.881021
Epoch  700/2000 Cost: 3.695124
Epoch  800/2000 Cost: 3.519025
Epoch  900/2000 Cost: 3.352130
Epoch 1000/2000 Cost: 3.194023
Epoch 1100/2000 Cost: 3.044178
Epoch 1200/2000 Cost: 2.902206
Epoch 1300/2000 Cost: 2.767665
Epoch 1400/2000 Cost: 2.640176
Epoch 1500/2000 Cost: 2.519374
Epoch 1600/2000 Cost: 2.404892
Epoch 1700/2000 Cost: 2.296402
Epoch 1800/2000 Cost: 2.193589
Epoch 1900/2000 Cost: 2.096157


In [23]:
## 미니 배치와 데이터 로드
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

dataset=TensorDataset(x_train, y_train)
dataloader=DataLoader(dataset, batch_size=2, shuffle=True)

model=nn.Linear(3,1)
optimizer=torch.optim.SGD(model.parameters(),lr=1e-5)

In [24]:
epochs=20

for epoch in range(epochs+1):
  for batch_idx,samples in enumerate(dataloader):
    x_train, y_train=samples
    prediction=model(x_train)
    cost=F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 17469.966797
Epoch    0/20 Batch 2/3 Cost: 8140.236816
Epoch    0/20 Batch 3/3 Cost: 1212.567383
Epoch    1/20 Batch 1/3 Cost: 659.749268
Epoch    1/20 Batch 2/3 Cost: 230.146149
Epoch    1/20 Batch 3/3 Cost: 55.642822
Epoch    2/20 Batch 1/3 Cost: 22.033173
Epoch    2/20 Batch 2/3 Cost: 10.638145
Epoch    2/20 Batch 3/3 Cost: 0.314384
Epoch    3/20 Batch 1/3 Cost: 2.670478
Epoch    3/20 Batch 2/3 Cost: 1.942718
Epoch    3/20 Batch 3/3 Cost: 0.204369
Epoch    4/20 Batch 1/3 Cost: 0.196425
Epoch    4/20 Batch 2/3 Cost: 2.998143
Epoch    4/20 Batch 3/3 Cost: 0.793023
Epoch    5/20 Batch 1/3 Cost: 0.693650
Epoch    5/20 Batch 2/3 Cost: 1.723843
Epoch    5/20 Batch 3/3 Cost: 0.571300
Epoch    6/20 Batch 1/3 Cost: 1.825678
Epoch    6/20 Batch 2/3 Cost: 0.735749
Epoch    6/20 Batch 3/3 Cost: 0.001638
Epoch    7/20 Batch 1/3 Cost: 0.960888
Epoch    7/20 Batch 2/3 Cost: 0.199898
Epoch    7/20 Batch 3/3 Cost: 2.913331
Epoch    8/20 Batch 1/3 Cost: 1.245124
Epoch   

In [25]:
new_var=torch.FloatTensor([73,80,75])
pred_y=model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([151.8986], grad_fn=<AddBackward0>)


In [26]:
## 커스텀 데이터셋

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class CustomDataset(Dataset):
  def __init__(self):
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  def __len__(self):
    return len(self.x_data)

  def __getitem__(self,idx):
    x=torch.Tensor(self.x_data[idx])
    y=torch.Tensor(self.y_data[idx])
    return x, y

In [27]:
dataset=CustomDataset()
dataloader=DataLoader(dataset, batch_size=2, shuffle=True)

model=torch.nn.Linear(3,1)
optimizer=torch.optim.SGD(model.parameters(),lr=1e-5)
epochs=20

for epoch in range(epochs):
  for batch_idx, sample in enumerate(dataloader):
    x_train, y_train=sample
    prediction=model(x_train)
    cost=F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 27335.189453
Epoch    0/20 Batch 2/3 Cost: 8715.619141
Epoch    0/20 Batch 3/3 Cost: 1490.101807
Epoch    1/20 Batch 1/3 Cost: 921.437439
Epoch    1/20 Batch 2/3 Cost: 282.625549
Epoch    1/20 Batch 3/3 Cost: 134.892761
Epoch    2/20 Batch 1/3 Cost: 14.906353
Epoch    2/20 Batch 2/3 Cost: 14.312960
Epoch    2/20 Batch 3/3 Cost: 5.781010
Epoch    3/20 Batch 1/3 Cost: 1.475286
Epoch    3/20 Batch 2/3 Cost: 5.480006
Epoch    3/20 Batch 3/3 Cost: 0.541326
Epoch    4/20 Batch 1/3 Cost: 0.501543
Epoch    4/20 Batch 2/3 Cost: 2.690190
Epoch    4/20 Batch 3/3 Cost: 8.012106
Epoch    5/20 Batch 1/3 Cost: 2.045734
Epoch    5/20 Batch 2/3 Cost: 4.247608
Epoch    5/20 Batch 3/3 Cost: 0.291477
Epoch    6/20 Batch 1/3 Cost: 0.613240
Epoch    6/20 Batch 2/3 Cost: 4.894110
Epoch    6/20 Batch 3/3 Cost: 0.052961
Epoch    7/20 Batch 1/3 Cost: 0.129937
Epoch    7/20 Batch 2/3 Cost: 4.872050
Epoch    7/20 Batch 3/3 Cost: 0.993875
Epoch    8/20 Batch 1/3 Cost: 2.349381
Epoch  

In [28]:
new_var =  torch.FloatTensor([[73, 80, 75]]) 
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.8715]], grad_fn=<AddmmBackward0>)
